'use strict';
const boardEl=document.querySelector('#board'),statusEl=document.querySelector('#status'),resultEl=document.querySelector('#result');
const palette = window.ArcadeGameColors;
const game={board:Array(9).fill(null),turn:0,mode:'solo',over:false,started:Date.now(),moves:0,scores:[0,0],colors:['#fffdf8','#d76b45']};
const online={socket:null,side:0,code:'',token:'',gamertags:[null,null]};
const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]], win=b=>lines.find(line=>b[line[0]]&&line.every(i=>b[i]===b[line[0]]));
function render(){boardEl.replaceChildren(...game.board.map((mark,i)=>{const b=document.createElement('button');b.className='cell';b.dataset.cell=i;b.setAttribute('role','gridcell');b.textContent=mark||'';b.style.setProperty('--mark',game.colors[mark==='O'?1:0]);b.disabled=game.over||Boolean(mark)||(game.mode==='online'&&game.turn!==online.side)||(game.mode==='solo'&&game.turn===1);if(win(game.board)?.includes(i))b.classList.add('win');return b;}));document.querySelector('#score-x').textContent=game.scores[0];document.querySelector('#score-o').textContent=game.scores[1];}
function finish(outcome){game.over=true;const draw=outcome===null;if(!draw)game.scores[outcome]++;render();const localPlayer=game.mode==='duo'?outcome:game.mode==='online'?online.side:0,won=!draw&&outcome===localPlayer;resultEl.hidden=false;resultEl.querySelector('strong').textContent=draw?'A perfect draw.':won?'You win!':game.mode==='duo'?`${outcome?'O':'X'} wins!`:'Opponent wins';resultEl.querySelector('span').textContent=`${game.moves} moves · ${Math.max(1,Math.round((Date.now()-game.started)/1000))} seconds`;window.Arcade?.record({game:'tictactoe',won,details:{mode:game.mode==='solo'?`solo-${document.querySelector('#difficulty').value}`:game.mode,moves:Math.max(3,game.moves),seconds:Math.max(1,Math.round((Date.now()-game.started)/1000)),outcome:draw?'draw':won?'win':'loss'}}).catch(()=>{});}
function afterMove(){const line=win(game.board);if(line)return finish(game.board[line[0]]==='X'?0:1);if(game.board.every(Boolean))return finish(null);game.turn=1-game.turn;statusEl.textContent=`${game.turn?'O':'X'} to move.`;render();if(game.mode==='solo'&&game.turn===1)setTimeout(computerMove,300);}
function move(i){if(game.over||game.board[i])return;game.board[i]=game.turn?'O':'X';game.moves++;afterMove();}
function scoreBoard(board,depth){const line=win(board);if(line)return board[line[0]]==='O'?10-depth:depth-10;if(board.every(Boolean))return 0;return null;}
function minimax(board,isO,depth=0){const score=scoreBoard(board,depth);if(score!==null)return score;const values=board.map((v,i)=>v?null:(board[i]=isO?'O':'X',(()=>{const s=minimax(board,!isO,depth+1);board[i]=null;return s;})())).filter(v=>v!==null);return isO?Math.max(...values):Math.min(...values);}
function computerMove(){const open=game.board.map((v,i)=>v?null:i).filter(v=>v!==null),level=document.querySelector('#difficulty').value;let choice;if(level==='easy'||(level==='medium'&&Math.random()<.45))choice=open[Math.floor(Math.random()*open.length)];else choice=open.reduce((best,i)=>{game.board[i]='O';const s=minimax(game.board,false);game.board[i]=null;return s>best.score?{i,score:s}:best;},{i:open[0],score:-Infinity}).i;move(choice);}
function reset(){Object.assign(game,{board:Array(9).fill(null),turn:0,over:false,started:Date.now(),moves:0});resultEl.hidden=true;statusEl.textContent=game.mode==='online'?'Ready up to begin.':'X to move.';render();}
boardEl.addEventListener('click',e=>{const i=Number(e.target.dataset.cell);if(!Number.isInteger(i))return;if(game.mode==='online')send({type:'move',cell:i});else move(i);});document.querySelector('#new-game').onclick=reset;
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{game.mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#online-panel').hidden=game.mode!=='online';document.querySelector('.difficulty').hidden=game.mode!=='solo';if(game.mode==='online')refreshRooms();reset();});
document.querySelectorAll('.player-color').forEach((picker,side)=>{const menu=picker.querySelector('.color-menu'),trigger=picker.querySelector('.color-trigger');palette.forEach(({name,value:color})=>{const b=document.createElement('button');b.className='swatch';b.style.setProperty('--swatch',color);b.title=name;b.onclick=()=>{game.colors[side]=color;trigger.style.setProperty('--selected-color',color);menu.hidden=true;if(game.mode==='online'&&side===online.side)send({type:'color',color});render();};menu.querySelector('.swatches').append(b);});trigger.onclick=()=>menu.hidden=!menu.hidden;});
function send(message){if(online.socket?.readyState===WebSocket.OPEN)online.socket.send(JSON.stringify(message));}
function connect(action){const scheme=location.protocol==='https:'?'wss:':'ws:';online.socket=new WebSocket(`${scheme}//${location.host}/ws/tictactoe`);document.querySelector('#connection').textContent='Connecting…';online.socket.onopen=()=>send(action);online.socket.onmessage=e=>handle(JSON.parse(e.data));online.socket.onclose=()=>document.querySelector('#connection').textContent='Offline';}
function handle(message){if(message.type==='session'){Object.assign(online,{side:message.side,code:message.roomCode,token:message.playerToken,gamertags:message.gamertags});sessionStorage.setItem('tic-online',JSON.stringify({roomCode:online.code,playerToken:online.token}));document.querySelector('#lobby').hidden=true;document.querySelector('#room').hidden=false;document.querySelector('#room-code').textContent=online.code;document.querySelector('#connection').textContent='Connected';}else if(message.type==='state'){const wasOver=game.over;Object.assign(game,message.state);game.moves=game.board.filter(Boolean).length;render();if(game.over&&!wasOver)finish(game.winner);else statusEl.textContent=game.running?(game.turn===online.side?'Your turn.':'Opponent’s turn.'):'Both players must ready up.';}else if(message.type==='room-status'){online.gamertags=message.gamertags;statusEl.textContent=message.players[1-online.side]?'Opponent connected. Ready up!':'Waiting for an opponent…';}else if(message.type==='error')statusEl.textContent=message.message;else if(message.type==='peer-left')statusEl.textContent='Opponent disconnected. Waiting for reconnection…';else if(message.type==='room-closed'){statusEl.textContent=message.reason;leave();}}
async function refreshRooms(){const list=document.querySelector('#rooms');list.innerHTML='<p>Loading rooms…</p>';try{const {rooms}=await fetch('/api/tictactoe/rooms').then(r=>r.json());list.replaceChildren(...rooms.map(room=>{const item=document.createElement('div');item.className='public-room';item.innerHTML=`<div><strong>${room.code}</strong><span>${room.players}/2 players</span></div><button class="secondary-button">Join</button>`;item.querySelector('button').onclick=()=>connect({type:'join-room',roomCode:room.code});return item;}));if(!rooms.length)list.innerHTML='<p>No public rooms yet.</p>';}catch{list.innerHTML='<p>Rooms unavailable.</p>';}}
document.querySelector('#refresh').onclick=refreshRooms;document.querySelector('#visibility').onchange=e=>document.querySelector('#create-pass').hidden=e.target.value==='public';document.querySelector('#create').onclick=()=>connect({type:'create-room',visibility:document.querySelector('#visibility').value,passcode:document.querySelector('#create-pass').value});document.querySelector('#join').onclick=()=>connect({type:'join-room',roomCode:document.querySelector('#code').value,passcode:document.querySelector('#join-pass').value});document.querySelector('#ready').onclick=()=>send({type:game.over?'rematch':'ready'});function leave(){send({type:'leave'});online.socket?.close();document.querySelector('#room').hidden=true;document.querySelector('#lobby').hidden=false;}document.querySelector('#leave').onclick=leave;
document.querySelector('#share').onclick=async()=>{const canvas=window.ResultShare.tictactoe({board:game.board,colors:game.colors,moves:game.moves,outcome:resultEl.querySelector('strong').textContent});try{await window.ResultShare.share({image:canvas,filename:'tic-tac-toe-result.png',title:'My Tic-tac-toe result',text:`${resultEl.querySelector('strong').textContent} in ${game.moves} moves`});}catch{}};
reset();
