'use strict';
const boardEl=document.querySelector('#board'),statusEl=document.querySelector('#status'),resultEl=document.querySelector('#result');
const palette = window.ArcadeGameColors;
const audio=window.ArcadeAudio;
const game={board:Array(9).fill(null),turn:0,mode:'solo',over:false,started:Date.now(),moves:0,scores:[0,0],colors:['#fffdf8','#d76b45']};
const online={socket:null,side:0,code:'',token:'',gamertags:[null,null],reconnectTimer:null,intentionalClose:false,awaitingResumeState:false};
const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]], win=b=>lines.find(line=>b[line[0]]&&line.every(i=>b[i]===b[line[0]]));
function render(){boardEl.replaceChildren(...game.board.map((mark,i)=>{const b=document.createElement('button');b.className='cell';b.dataset.cell=i;b.setAttribute('role','gridcell');b.textContent=mark||'';b.style.setProperty('--mark',game.colors[mark==='O'?1:0]);b.disabled=game.over||Boolean(mark)||(game.mode==='online'&&game.turn!==online.side)||(game.mode==='solo'&&game.turn===1);if(win(game.board)?.includes(i))b.classList.add('win');return b;}));document.querySelector('#score-x').textContent=game.scores[0];document.querySelector('#score-o').textContent=game.scores[1];}
function finish(outcome,record=true){game.over=true;const draw=outcome===null;if(!draw&&record)game.scores[outcome]++;render();const localPlayer=game.mode==='duo'?outcome:game.mode==='online'?online.side:0,won=!draw&&outcome===localPlayer;resultEl.hidden=false;resultEl.querySelector('strong').textContent=draw?'A perfect draw.':won?'You win!':game.mode==='duo'?`${outcome?'O':'X'} wins!`:'Opponent wins';resultEl.querySelector('span').textContent=`${game.moves} moves · ${Math.max(1,Math.round((Date.now()-game.started)/1000))} seconds`;audio?.setScene('complete');if(record)audio?.cue(draw?'draw':won||game.mode==='duo'?'win':'loss');if(record)window.Arcade?.record({game:'tictactoe',won,details:{mode:game.mode==='solo'?`solo-${document.querySelector('#difficulty').value}`:game.mode,moves:Math.max(3,game.moves),seconds:Math.max(1,Math.round((Date.now()-game.started)/1000)),outcome:draw?'draw':won?'win':'loss'}}).catch(()=>{});}
function afterMove(){const line=win(game.board);if(line)return finish(game.board[line[0]]==='X'?0:1);if(game.board.every(Boolean))return finish(null);game.turn=1-game.turn;statusEl.textContent=`${game.turn?'O':'X'} to move.`;render();if(game.mode==='solo'&&game.turn===1)setTimeout(computerMove,300);}
function move(i){if(game.over||game.board[i])return;const side=game.turn;game.board[i]=side?'O':'X';game.moves++;audio?.cue('mark',{side});audio?.setScene('active',{intensity:.15+game.moves/9*.65,danger:game.moves/9});afterMove();}
function scoreBoard(board,depth){const line=win(board);if(line)return board[line[0]]==='O'?10-depth:depth-10;if(board.every(Boolean))return 0;return null;}
function minimax(board,isO,depth=0){const score=scoreBoard(board,depth);if(score!==null)return score;const values=board.map((v,i)=>v?null:(board[i]=isO?'O':'X',(()=>{const s=minimax(board,!isO,depth+1);board[i]=null;return s;})())).filter(v=>v!==null);return isO?Math.max(...values):Math.min(...values);}
function computerMove(){const open=game.board.map((v,i)=>v?null:i).filter(v=>v!==null),level=document.querySelector('#difficulty').value;let choice;if(level==='easy'||(level==='medium'&&Math.random()<.45))choice=open[Math.floor(Math.random()*open.length)];else choice=open.reduce((best,i)=>{game.board[i]='O';const s=minimax(game.board,false);game.board[i]=null;return s>best.score?{i,score:s}:best;},{i:open[0],score:-Infinity}).i;move(choice);}
function reset(){Object.assign(game,{board:Array(9).fill(null),turn:0,over:false,started:Date.now(),moves:0});resultEl.hidden=true;statusEl.textContent=game.mode==='online'?'Ready up to begin.':'X to move.';audio?.setPaused(false);audio?.setScene('active',{intensity:.1,danger:0});render();}
boardEl.addEventListener('click',e=>{const i=Number(e.target.dataset.cell);if(!Number.isInteger(i))return;if(game.mode==='online')send({type:'move',cell:i});else move(i);});document.querySelector('#new-game').onclick=()=>{if(game.mode==='online'){if(game.over)send({type:'rematch'});return;}reset();};
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{game.mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#online-panel').hidden=game.mode!=='online';document.querySelector('.difficulty').hidden=game.mode!=='solo';if(game.mode==='online')refreshRooms();reset();});
document.querySelectorAll('.player-color').forEach((picker,side)=>{const menu=picker.querySelector('.color-menu'),trigger=picker.querySelector('.color-trigger');palette.forEach(({name,value:color})=>{const b=document.createElement('button');b.className='swatch';b.style.setProperty('--swatch',color);b.title=name;b.onclick=()=>{game.colors[side]=color;trigger.style.setProperty('--selected-color',color);menu.hidden=true;if(game.mode==='online'&&side===online.side)send({type:'color',color});render();};menu.querySelector('.swatches').append(b);});trigger.onclick=()=>menu.hidden=!menu.hidden;});
function send(message){if(online.socket?.readyState===WebSocket.OPEN)online.socket.send(JSON.stringify(message));}
function setConnection(label,state='offline'){OnlineRooms.setConnection(document.querySelector('#connection'),label,state);}
function connect(action){if(online.socket&&online.socket.readyState<WebSocket.CLOSING)online.socket.close();online.intentionalClose=false;online.awaitingResumeState=action.type==='resume';setConnection('Connecting…','connecting');const scheme=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${scheme}//${location.host}/ws/tictactoe`);online.socket=socket;socket.onopen=()=>send(action);socket.onmessage=e=>{try{handle(JSON.parse(e.data));}catch{statusEl.textContent='Received an invalid server update.';}};socket.onclose=()=>{if(socket!==online.socket)return;if(online.intentionalClose||game.mode!=='online'){setConnection('Offline');return;}setConnection('Reconnecting…','connecting');if(online.code&&online.token)online.reconnectTimer=setTimeout(()=>connect({type:'resume',roomCode:online.code,playerToken:online.token}),1000);else setConnection('Offline');};}
function handle(message){if(message.type==='session'){Object.assign(online,{side:message.side,code:message.roomCode,token:message.playerToken,gamertags:message.gamertags});sessionStorage.setItem('tic-online',JSON.stringify({roomCode:online.code,playerToken:online.token}));document.querySelector('#lobby').hidden=true;document.querySelector('#room').hidden=false;document.querySelector('#room-code').textContent=online.code;setConnection('Connected','online');const url=new URL(location.href);url.searchParams.set('room',online.code);history.replaceState(null,'',url);statusEl.textContent=message.side===0?'Room created. Share the invite and wait for your opponent.':'Joined room. Ready up when you are set.';}else if(message.type==='state'){const wasOver=game.over,resumedSnapshot=online.awaitingResumeState,previousBoard=[...game.board];online.awaitingResumeState=false;Object.assign(game,message.state);game.moves=game.board.filter(Boolean).length;if(game.running)resultEl.hidden=true;if(!resumedSnapshot){const changed=game.board.findIndex((mark,index)=>mark&&!previousBoard[index]);if(changed>=0)audio?.cue('mark',{side:game.board[changed]==='O'?1:0});}audio?.setScene(game.over?'complete':'active',{intensity:.15+game.moves/9*.65,danger:game.moves/9});render();if(game.over&&!wasOver)finish(game.winner,!resumedSnapshot);else statusEl.textContent=game.running?(game.turn===online.side?'Your turn.':'Opponent’s turn.'):game.over?'Choose rematch to play again.':'Both players must ready up.';}else if(message.type==='room-status'){online.gamertags=message.gamertags;statusEl.textContent=message.players[1-online.side]?'Opponent connected. Ready up!':'Waiting for an opponent…';}else if(message.type==='error')statusEl.textContent=message.message;else if(message.type==='peer-left')statusEl.textContent='Opponent disconnected. Waiting for reconnection…';else if(message.type==='room-closed'){statusEl.textContent=message.reason;leave(false);}}
async function refreshRooms(){const list=document.querySelector('#rooms');list.innerHTML='<p>Loading rooms…</p>';try{const {rooms}=await fetch('/api/tictactoe/rooms').then(r=>r.json());OnlineRooms.renderRooms(list,rooms,code=>connect({type:'join-room',roomCode:code}));}catch{list.innerHTML='<p>Rooms unavailable.</p>';}}
document.querySelector('#refresh').onclick=refreshRooms;document.querySelector('#visibility').onchange=e=>document.querySelector('#create-pass').hidden=e.target.value==='public';document.querySelector('#create').onclick=()=>{const visibility=document.querySelector('#visibility').value,result=OnlineRooms.validateRoom(visibility,document.querySelector('#create-pass').value);if(!result.ok){statusEl.textContent=result.message;return;}connect({type:'create-room',visibility,passcode:result.passcode});};document.querySelector('#join').onclick=()=>{const result=OnlineRooms.validateJoin(document.querySelector('#code').value);if(!result.ok){statusEl.textContent=result.message;return;}connect({type:'join-room',roomCode:result.code,passcode:document.querySelector('#join-pass').value.trim()});};document.querySelector('#ready').onclick=()=>send({type:game.over?'rematch':'ready'});function leave(notify=true){clearTimeout(online.reconnectTimer);if(notify)send({type:'leave'});online.intentionalClose=true;online.socket?.close();sessionStorage.removeItem('tic-online');Object.assign(online,{code:'',token:''});document.querySelector('#room').hidden=true;document.querySelector('#lobby').hidden=false;setConnection('Offline');history.replaceState(null,'',OnlineRooms.clearInvite());refreshRooms();}document.querySelector('#leave').onclick=()=>leave();
document.querySelector('#copy-invite').onclick=async()=>{try{await OnlineRooms.copyInvite(online.code);statusEl.textContent='Invite link copied.';}catch{statusEl.textContent='Could not copy the invite link. Copy it from the address bar instead.';}};
document.querySelector('#share').onclick=async()=>{const canvas=window.ResultShare.tictactoe({board:game.board,colors:game.colors,moves:game.moves,outcome:resultEl.querySelector('strong').textContent});try{await window.ResultShare.share({image:canvas,filename:'tic-tac-toe-result.png',title:'My Tic-tac-toe result',text:`${resultEl.querySelector('strong').textContent} in ${game.moves} moves`});}catch{}};
reset();
const invitedRoom=new URLSearchParams(location.search).get('room');let savedSession=null;try{savedSession=JSON.parse(sessionStorage.getItem('tic-online'));}catch{sessionStorage.removeItem('tic-online');}if(invitedRoom){document.querySelector('[data-mode="online"]').click();const normalized=OnlineRooms.normalizeCode(invitedRoom);if(savedSession?.roomCode===normalized&&savedSession.playerToken){Object.assign(online,{code:savedSession.roomCode,token:savedSession.playerToken});connect({type:'resume',roomCode:online.code,playerToken:online.token});}else{document.querySelector('#code').value=normalized;statusEl.textContent='Invitation loaded. Join when you are ready.';}}
