'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { BattleTanksRooms } = require('../server/battle-tanks-rooms');
const core = require('../battle-tanks/scripts/game');
const socket = () => ({ readyState: 1, messages: [], send(body) { this.messages.push(JSON.parse(body)); }, close() {} });
function started(options = {}) { const rooms = new BattleTanksRooms({ random: () => 0, ...options }), host = rooms.create(socket(), { visibility: 'public', user: { id: 1, gamertag: 'Host' } }), guest = rooms.join(host.room.code, socket(), '', { id: 2, gamertag: 'Guest' }); rooms.ready(host.room, host.player); rooms.ready(host.room, guest.player); return { rooms, host, guest }; }
const command = (room, type, extra = {}) => ({ type, matchId: room.matchId, turnId: room.turnId, ...extra });

test('predicts smooth projectile positions between authoritative snapshots', () => {
    const projectile = { x: 100, y: 200, vx: 300, vy: -100, owner: 0 };
    assert.deepEqual(core.predictProjectile(projectile, .05), { x: 115, y: 195.2625, vx: 300, vy: -89.5, owner: 0 });
    assert.deepEqual(projectile, { x: 100, y: 200, vx: 300, vy: -100, owner: 0 }, 'render prediction must not mutate authoritative state');
});

test('creates public/private rooms without exposing secrets and rejects full rooms', () => { let value = 0; const rooms = new BattleTanksRooms({ random: () => (value += .01) }); const pub = rooms.create(socket(), { visibility: 'public', user: { gamertag: 'Host' } }); const secret = rooms.create(socket(), { passcode: 'shell7' }); assert.deepEqual(rooms.publicRooms().map(item => item.code), [pub.room.code]); assert.throws(() => rooms.join(secret.room.code, socket(), 'bad'), /passcode/i); rooms.join(pub.room.code, socket()); assert.throws(() => rooms.join(pub.room.code, socket()), /full/i); assert.equal(JSON.stringify(rooms.publicRooms()).includes('shell7'), false); });
test('requires both players and alternates authoritative turns', () => { const rooms = new BattleTanksRooms({ random: () => 0 }), host = rooms.create(socket(), { visibility: 'public' }), guest = rooms.join(host.room.code, socket()); assert.equal(rooms.ready(host.room, host.player), false); assert.equal(rooms.ready(host.room, guest.player), true); assert.throws(() => rooms.command(host.room, guest.player, command(host.room, 'move', { direction: 'forward' })), /turn/i); rooms.command(host.room, host.player, command(host.room, 'move', { direction: 'forward' })); assert.ok(host.room.game.tanks[0].x > 115); rooms.command(host.room, host.player, command(host.room, 'fire')); while (host.room.game.phase === 'projectile-flight') rooms.tick(1 / 60); assert.equal(host.room.game.activePlayer, 1); assert.equal(host.room.turnId, 2); });
test('rejects stale, invalid, and excessive commands', () => { const { rooms, host } = started(); assert.throws(() => rooms.command(host.room, host.player, { type: 'fire', matchId: 0, turnId: 0 }), /stale/i); assert.throws(() => rooms.command(host.room, host.player, command(host.room, 'aim', { angle: Infinity, power: 50 })), /invalid/i); for (let i = 0; i < 29; i += 1) rooms.command(host.room, host.player, command(host.room, 'aim', { angle: 45, power: 60 })); assert.throws(() => rooms.command(host.room, host.player, command(host.room, 'aim', { angle: 45, power: 60 })), /many/i); });
test('pauses on disconnect, resumes securely, and ignores an old socket close', () => { const { rooms, host, guest } = started(); const old = guest.player.socket; rooms.disconnect(host.room, guest.player, old); assert.equal(host.room.paused, true); assert.throws(() => rooms.command(host.room, host.player, command(host.room, 'fire')), /paused/i); const replacement = socket(); rooms.resume(host.room.code, guest.player.token, replacement); assert.equal(host.room.paused, false); assert.equal(rooms.disconnect(host.room, guest.player, old), false); assert.equal(guest.player.connected, true); });
test('expires abandoned rooms after the reconnect grace period', () => { const { rooms, host, guest } = started({ reconnectMs: 10 }); rooms.disconnect(host.room, guest.player); rooms.tick(0, guest.player.disconnectedAt + 11); assert.equal(rooms.rooms.has(host.room.code), false); });
test('records each authenticated online result once from authoritative state', () => { const results = [], { rooms, host } = started({ recordResult: (id, result) => results.push({ id, result }) }); host.room.stats[0].shots = 2; host.room.stats[0].hits = 2; host.room.stats[1].shots = 1; host.room.stats[1].damageTaken = 100; host.room.game.tanks[1].health = 0; host.room.game.winner = 0; host.room.game.phase = 'game-over'; rooms.finish(host.room); rooms.finish(host.room); assert.equal(results.length, 2); assert.deepEqual(results.map(item => item.result.won), [true, false]); assert.ok(results.every(item => item.result.details.mode === 'online')); });
test('server projectile collision broadcasts the resolved state and advances once', () => { const { rooms, host, guest } = started(); const target = host.room.game.tanks[1]; host.room.stats[0].shots = 1; host.room.game.projectile = { x: target.x - 20, y: target.y + core.TANK_H / 2, vx: 200, vy: 0, owner: 0 }; host.room.game.phase = 'projectile-flight'; rooms.tick(.2); assert.equal(target.health, 50); assert.equal(host.room.stats[0].hits, 1); assert.equal(host.room.game.activePlayer, 1); for (const player of [host.player, guest.player]) { const update = player.socket.messages.at(-1); assert.equal(update.type, 'state'); assert.equal(update.state.phase, 'aiming'); assert.equal(update.state.turnId, 2); } const turn = host.room.turnId; rooms.tick(.2); assert.equal(host.room.turnId, turn); });
