'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {TicTacToeRooms,winner}=require('../server/tictactoe-rooms');
const socket=()=>({readyState:1,messages:[],send(body){this.messages.push(JSON.parse(body));},close(){}});
test('keeps the tic-tac-toe board and cells sized on narrow screens',()=>{const css=fs.readFileSync('tictactoe/styles.css','utf8');assert.match(css,/\.arena-wrap\{[^}]*width:100%;min-width:0;aspect-ratio:1/);assert.match(css,/grid-template:repeat\(3,minmax\(0,1fr\)\)\/repeat\(3,minmax\(0,1fr\)\)/);assert.match(css,/\.cell\{[^}]*min-width:0;min-height:0/);});
test('offers invite links and safely restores interrupted online sessions',()=>{const html=fs.readFileSync('tictactoe/index.html','utf8'),client=fs.readFileSync('tictactoe/scripts/app.js','utf8'),server=fs.readFileSync('server/index.js','utf8');assert.match(html,/id="copy-invite"/);assert.match(client,/navigator\.clipboard\.writeText/);assert.match(client,/awaitingResumeState=action\.type==='resume'/);assert.match(client,/finish\(game\.winner,!resumedSnapshot\)/);assert.ok(server.indexOf('socket.isAlive = true')<server.indexOf("pathname === '/ws/tictactoe'"),'heartbeat must be installed before routing tic-tac-toe sockets');});
test('detects all tic-tac-toe winning lines',()=>{assert.deepEqual(winner(['X','X','X',null,null,null,null,null,null]),[0,1,2]);assert.deepEqual(winner(['O',null,null,null,'O',null,null,null,'O']),[0,4,8]);assert.equal(winner(['X','O','X','X','O','O','O','X','X']),null);});
test('runs an authoritative online tic-tac-toe match and rematch',()=>{const rooms=new TicTacToeRooms({random:()=>0});const host=rooms.create(socket(),{visibility:'public'}),guest=rooms.join(host.room.code,socket());rooms.ready(host.room,host.player);assert.equal(rooms.ready(host.room,guest.player),true);assert.equal(host.room.turn,0);const started=rooms.state(host.room).started;assert.equal(typeof started,'number');rooms.move(host.room,host.player,0);rooms.move(host.room,guest.player,3);rooms.move(host.room,host.player,1);rooms.move(host.room,guest.player,4);rooms.move(host.room,host.player,2);assert.equal(host.room.winner,0);assert.deepEqual(host.room.winningLine,[0,1,2]);assert.equal(rooms.state(host.room).started,started,'completed and resumed snapshots preserve the match start time');assert.throws(()=>rooms.move(host.room,guest.player,5),/not active/i);rooms.ready(host.room,host.player);rooms.ready(host.room,guest.player);assert.equal(host.room.turn,1);assert.deepEqual(host.room.board,Array(9).fill(null));assert.ok(rooms.state(host.room).started>=started);});
test('protects private tic-tac-toe rooms and validates turns',()=>{const rooms=new TicTacToeRooms({random:()=>0});const host=rooms.create(socket(),{passcode:'grid7'});assert.throws(()=>rooms.join(host.room.code,socket(),'bad'),/passcode/i);const guest=rooms.join(host.room.code,socket(),'grid7');rooms.ready(host.room,host.player);rooms.ready(host.room,guest.player);assert.throws(()=>rooms.move(host.room,guest.player,0),/turn/i);rooms.move(host.room,host.player,0);assert.throws(()=>rooms.move(host.room,guest.player,0),/unavailable/i);});
