(function(root){
'use strict';
const api=root.BattleTanksCore;
if(!api)throw new Error('Battle Tanks mechanics failed to load.');
const {STATE_VERSION,WIDTH,HEIGHT,TANK_W,TANK_H,PROJECTILE_R,STARTING_HEALTH,TERRAIN_STEP,PICKUP_SIZE,POWER_UP_CATALOG,WEAPON_REGISTRY,terrainHeightAt,tankYAt,createInitialState,beginTurn,tankBounds,moveTank,collectPickup,adjustAim,adjustPower,selectWeapon,fireProjectile,predictProjectile,stepPhysics,resetMatch,activatePowerUp,advancePickupSchedule,endTurnEffects}=api;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),status=document.querySelector('#status'),fire=document.querySelector('#fire'),fullscreenFire=document.querySelector('#fullscreen-fire'),rematch=document.querySelector('#rematch'),arena=document.querySelector('#arena'),shareButton=document.querySelector('#share-result'),fullscreenButton=document.querySelector('#fullscreen');const state=createInitialState();let last=performance.now(),accumulator=0,dragging=false,mode='local',socket=null,onlineSession=null,mySide=null,onlineProjectileSample=null;
const tankColors=[window.ArcadeGameColors[3].value,window.ArcadeGameColors[1].value];
let arenaColors,lastImpactSerial=0;
// Cards remain for 3.6 seconds of active viewing; focus, hover, and hidden tabs pause that interval.
const POWER_CARD_INTERVAL=3600,powerCardLayer=document.querySelector('#power-card-layer'),powerCard=document.querySelector('#power-card'),dismissPowerCardButton=document.querySelector('#dismiss-power-card'),powerCardQueue=[];
let currentPowerCard=null,powerCardTimer=null,powerCardRemaining=POWER_CARD_INTERVAL,powerCardStarted=0,presentationMatchId=null,highestPresentedEventId=0;
const iconGlyphs={health:'♥',shield:'⬢',hidden:'◈','heavy-shell':'●',homing:'➤',laser:'⌁','wide-blast':'✹',damage:'⚡',blast:'✺'};
function pausePowerCardTimer(){if(!powerCardTimer)return;clearTimeout(powerCardTimer);powerCardTimer=null;powerCardRemaining=Math.max(0,powerCardRemaining-(performance.now()-powerCardStarted));}
function resumePowerCardTimer(){if(!currentPowerCard||powerCardTimer||document.hidden||powerCard.matches(':hover')||powerCard.contains(document.activeElement))return;powerCardStarted=performance.now();powerCardTimer=setTimeout(dismissPowerCard,powerCardRemaining);}
function dismissPowerCard(){if(!currentPowerCard)return;clearTimeout(powerCardTimer);powerCardTimer=null;powerCardLayer.hidden=true;currentPowerCard=null;showNextPowerCard();}
function showNextPowerCard(){if(currentPowerCard||!powerCardQueue.length)return;currentPowerCard=powerCardQueue.shift();const event=currentPowerCard,values=event.generatedValues||{};powerCard.dataset.theme=event.theme;document.querySelector('#power-card-player').textContent=`Player ${event.player+1} acquired`;document.querySelector('#power-card-title').textContent=event.displayName;document.querySelector('#power-card-icon').textContent=iconGlyphs[event.iconKey]||'★';document.querySelector('#power-card-meta').textContent=`${event.rarity} · ${event.powerUpType}`;document.querySelector('#power-card-effect').textContent=event.effectDescription;document.querySelector('#power-card-values').innerHTML=Object.entries(values).map(([key,value])=>`<div><dt>${key.replace(/([A-Z])/g,' $1')}</dt><dd>${value}</dd></div>`).join('');document.querySelector('#power-card-live').textContent=`Player ${event.player+1} acquired ${event.displayName}: ${event.effectDescription}.`;powerCard.style.animation='none';void powerCard.offsetWidth;powerCard.style.removeProperty('animation');powerCardLayer.hidden=false;powerCardRemaining=POWER_CARD_INTERVAL;resumePowerCardTimer();}
function queueAcquisitionEvents(events=[]){events.filter(event=>Number.isSafeInteger(event.eventId)&&event.eventId>highestPresentedEventId&&!powerCardQueue.some(queued=>queued.eventId===event.eventId)&&event.eventId!==currentPowerCard?.eventId).sort((a,b)=>a.eventId-b.eventId).forEach(event=>{highestPresentedEventId=event.eventId;sessionStorage.setItem(`battle-tanks-presented-${presentationMatchId}`,String(highestPresentedEventId));powerCardQueue.push(event);});showNextPowerCard();}
function syncAcquisitionEvents(){const match=state.matchId??'local',room=mode==='online'?(onlineSession?.roomCode||'pending'):'local',presentationId=`${room}-${match}`;if(presentationId!==presentationMatchId){presentationMatchId=presentationId;highestPresentedEventId=Number(sessionStorage.getItem(`battle-tanks-presented-${presentationId}`))||0;powerCardQueue.length=0;dismissPowerCard();}queueAcquisitionEvents(state.acquisitionEvents);}
dismissPowerCardButton.addEventListener('click',dismissPowerCard);powerCard.addEventListener('mouseenter',pausePowerCardTimer);powerCard.addEventListener('mouseleave',resumePowerCardTimer);powerCard.addEventListener('focusin',pausePowerCardTimer);powerCard.addEventListener('focusout',()=>setTimeout(resumePowerCardTimer));document.addEventListener('visibilitychange',()=>document.hidden?pausePowerCardTimer():resumePowerCardTimer);

function updateArenaTheme(resolved=document.documentElement.dataset.colorMode,theme=document.documentElement.dataset.arcadeTheme){
    const palettes={
        playful:{dark:{skyTop:'#152c35',skyBottom:'#28443f',terrain:'#425b38',terrainEdge:'#a6bf82',barrier:'#746d68',barrierLine:'#d2c3b7',ink:'#f5fbf7',active:'#fff4a8',aim:'#fff4a8'},light:{skyTop:'#b9dadd',skyBottom:'#edf0d8',terrain:'#79935c',terrainEdge:'#405638',barrier:'#786c61',barrierLine:'#4d443d',ink:'#182720',active:'#ffffff',aim:'#173f35'}},
        cabinet:{dark:{skyTop:'#101329',skyBottom:'#272052',terrain:'#242d4d',terrainEdge:'#16e0bd',barrier:'#663a68',barrierLine:'#ffcf4a',ink:'#fff4d0',active:'#ffcf4a',aim:'#16e0bd'},light:{skyTop:'#ead8b1',skyBottom:'#f8c98c',terrain:'#7e8262',terrainEdge:'#382c42',barrier:'#8c6277',barrierLine:'#382c42',ink:'#382c42',active:'#fff3d6',aim:'#9b175d'}},
        calm:{dark:{skyTop:'#17231f',skyBottom:'#263c35',terrain:'#425b50',terrainEdge:'#9bb5ab',barrier:'#665f58',barrierLine:'#b8c4bf',ink:'#e5efeb',active:'#d9b968',aim:'#a1d1c3'},light:{skyTop:'#dce9e4',skyBottom:'#eef4f1',terrain:'#789d90',terrainEdge:'#405f55',barrier:'#8a8177',barrierLine:'#527068',ink:'#223a33',active:'#f8fbf9',aim:'#356f61'}}
    };
    arenaColors=(palettes[theme]||palettes.playful)[resolved]||palettes.playful.light;render();
}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function drawTank(tank,i){
    if(!tank||tank.concealed)return;
    const active=state.phase==='aiming'&&i===state.activePlayer,dir=i?-1:1,cx=tank.x+TANK_W/2,base=tank.y+TANK_H;
    ctx.save();
    if((state.activeEffects?.[i]||[]).some(effect=>effect.effect==='invisible'))ctx.globalAlpha=.35;
    const shield=(state.activeEffects?.[i]||[]).find(effect=>effect.effect==='absorb');if(shield){ctx.strokeStyle='#70ddff';ctx.setLineDash([9,5]);ctx.lineWidth=4;ctx.beginPath();ctx.arc(cx,tank.y+10,44,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=arenaColors.ink;ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(`SHIELD ${shield.remainingTurns}T · ${shield.remainingCapacity}`,cx,tank.y-39);}
    // Tracks, road wheels, sloped hull, and turret give each vehicle a sturdier silhouette.
    ctx.fillStyle='#17251f';roundedRect(tank.x-5,base-13,TANK_W+10,16,7);ctx.fill();
    for(let wheel=0;wheel<4;wheel+=1){ctx.fillStyle='#435048';ctx.beginPath();ctx.arc(tank.x+8+wheel*14,base-5,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#13201b';ctx.lineWidth=2;ctx.stroke();}
    ctx.fillStyle=tankColors[i];ctx.beginPath();ctx.moveTo(tank.x,base-14);ctx.lineTo(tank.x+8,base-26);ctx.lineTo(tank.x+TANK_W-8,base-26);ctx.lineTo(tank.x+TANK_W,base-14);ctx.closePath();ctx.fill();ctx.strokeStyle=arenaColors.ink;ctx.lineWidth=3;ctx.stroke();
    ctx.fillStyle=tankColors[i];roundedRect(cx-17,tank.y-3,34,17,7);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(cx-10,tank.y+1,15,3);
    const rad=tank.angle*Math.PI/180;ctx.strokeStyle=arenaColors.ink;ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(cx, tank.y+4);ctx.lineTo(cx+Math.cos(rad)*43*dir,tank.y-Math.sin(rad)*43);ctx.stroke();
    // Persistent dents, scorch and exposed metal scale with damage taken.
    if(tank.health<100){ctx.fillStyle='rgba(20,20,17,.72)';ctx.beginPath();ctx.arc(cx+(i?-9:9),tank.y+8,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e2a35f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cx-4,tank.y+8);ctx.lineTo(cx+5,tank.y+14);ctx.lineTo(cx,tank.y+21);ctx.stroke();}
    if(tank.health<=50){ctx.strokeStyle='#24241f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(tank.x+8,base-21);ctx.lineTo(tank.x+17,base-14);ctx.lineTo(tank.x+23,base-22);ctx.stroke();ctx.fillStyle='rgba(38,38,32,.26)';ctx.beginPath();ctx.arc(cx,tank.y-17,11,0,Math.PI*2);ctx.arc(cx+8,tank.y-27,8,0,Math.PI*2);ctx.fill();}
    if(active){ctx.strokeStyle=arenaColors.active;ctx.lineWidth=2;roundedRect(tank.x-7,tank.y-7,TANK_W+14,TANK_H+12,8);ctx.stroke();ctx.setLineDash([7,7]);ctx.strokeStyle=arenaColors.aim;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(cx+Math.cos(rad)*48*dir,tank.y-Math.sin(rad)*48);ctx.lineTo(cx+Math.cos(rad)*105*dir,tank.y-Math.sin(rad)*105);ctx.stroke();}
    ctx.restore();
}
function drawBarrier(barrier){
    const size=barrier.cellSize,ground=terrainHeightAt(state.arena,barrier.x+barrier.w/2),gradient=ctx.createLinearGradient(0,barrier.y,0,ground);
    gradient.addColorStop(0,arenaColors.barrier);gradient.addColorStop(.72,arenaColors.barrier);gradient.addColorStop(1,arenaColors.terrain);
    // Merge adjacent occupied cells into runs. This keeps the authoritative mask
    // while avoiding visible hairline seams between its small collision cells.
    const runs=[];for(let row=0;row<barrier.rows;row+=1){let start=-1;for(let column=0;column<=barrier.columns;column+=1){const filled=column<barrier.columns&&barrier.cells[row*barrier.columns+column];if(filled&&start<0)start=column;if(!filled&&start>=0){runs.push({row,start,end:column});start=-1;}}}
    ctx.fillStyle=gradient;runs.forEach(run=>ctx.fillRect(barrier.x+run.start*size,barrier.y+run.row*size,Math.min(barrier.w,run.end*size)-run.start*size,Math.min(size,barrier.h-run.row*size)));
    // Recessed courses add structure without drawing a rigid rectangle across
    // blast holes. Their contrast fades where the wall meets the earth.
    ctx.fillStyle=arenaColors.barrierLine;ctx.globalAlpha=.42;runs.forEach(run=>{if(run.row&&run.row*size%24<size)ctx.fillRect(barrier.x+run.start*size,barrier.y+run.row*size,Math.min(barrier.w,run.end*size)-run.start*size,2);});ctx.globalAlpha=1;
    // Trace only exposed material edges, including fresh crater boundaries.
    ctx.strokeStyle=arenaColors.barrierLine;ctx.globalAlpha=.55;ctx.lineWidth=1.5;ctx.beginPath();for(let row=0;row<barrier.rows;row+=1)for(let column=0;column<barrier.columns;column+=1){if(!barrier.cells[row*barrier.columns+column])continue;const x=barrier.x+column*size,y=barrier.y+row*size,right=Math.min(x+size,barrier.x+barrier.w),bottom=Math.min(y+size,barrier.y+barrier.h),occupied=(c,r)=>c>=0&&r>=0&&c<barrier.columns&&r<barrier.rows&&barrier.cells[r*barrier.columns+c];if(!occupied(column,row-1)){ctx.moveTo(x,y);ctx.lineTo(right,y);}if(!occupied(column-1,row)){ctx.moveTo(x,y);ctx.lineTo(x,bottom);}if(!occupied(column+1,row)){ctx.moveTo(right,y);ctx.lineTo(right,bottom);}}ctx.stroke();ctx.globalAlpha=1;
}
function renderArena(){
    const barrier=state.arena?.barrier,terrain=state.arena?.terrain;if(!barrier||!Array.isArray(terrain))return;const terrainY=x=>terrainHeightAt(state.arena,x);ctx.clearRect(0,0,WIDTH,HEIGHT);const sky=ctx.createLinearGradient(0,0,0,HEIGHT);sky.addColorStop(0,arenaColors.skyTop);sky.addColorStop(1,arenaColors.skyBottom);ctx.fillStyle=sky;ctx.fillRect(0,0,WIDTH,HEIGHT);drawBarrier(barrier);ctx.beginPath();ctx.moveTo(0,HEIGHT);ctx.lineTo(0,terrainY(0));terrain.forEach((height,index)=>ctx.lineTo(index*TERRAIN_STEP,height));ctx.lineTo(WIDTH,HEIGHT);ctx.closePath();ctx.fillStyle=arenaColors.terrain;ctx.fill();ctx.beginPath();terrain.forEach((height,index)=>index?ctx.lineTo(index*TERRAIN_STEP,height):ctx.moveTo(0,height));ctx.strokeStyle=arenaColors.terrainEdge;ctx.lineWidth=7;ctx.stroke();
}
function renderEffects(){(state.impacts||[]).slice(-4).filter(impact=>Number.isFinite(impact?.x)&&Number.isFinite(impact?.y)).forEach((impact,index)=>{ctx.save();ctx.globalAlpha=.08+index*.04;ctx.fillStyle='#ffcf70';ctx.beginPath();ctx.arc(impact.x,impact.y,5+index,0,Math.PI*2);ctx.fill();ctx.restore();});const segments=Array.isArray(state.laserPath?.segments)?state.laserPath.segments:[];if(segments.length){ctx.save();ctx.lineCap='round';segments.forEach(segment=>{if(!Number.isFinite(segment?.from?.x)||!Number.isFinite(segment?.from?.y)||!Number.isFinite(segment?.to?.x)||!Number.isFinite(segment?.to?.y))return;const energy=Number.isFinite(segment.energy)?segment.energy:1;ctx.globalAlpha=Math.max(.2,energy);ctx.strokeStyle='#fff3a0';ctx.lineWidth=2+4*energy;ctx.beginPath();ctx.moveTo(segment.from.x,segment.from.y);ctx.lineTo(segment.to.x,segment.to.y);ctx.stroke();});ctx.restore();}}
function renderPickups(){(state.pickups||[]).forEach(pickup=>{if(!Number.isFinite(pickup?.x)||!Number.isFinite(pickup?.y))return;const size=PICKUP_SIZE,left=pickup.x-size/2,top=pickup.y-size;ctx.save();ctx.shadowColor='#ffd36a';ctx.shadowBlur=18;const crate=ctx.createLinearGradient(left,top,left+size,pickup.y);crate.addColorStop(0,'#fff0a0');crate.addColorStop(.48,'#eaa83e');crate.addColorStop(1,'#a95c25');ctx.fillStyle=crate;ctx.strokeStyle='#392719';ctx.lineWidth=3;roundedRect(left,top,size,size,7);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='rgba(70,39,20,.75)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(left+5,top+5);ctx.lineTo(left+size-5,pickup.y-5);ctx.moveTo(left+size-5,top+5);ctx.lineTo(left+5,pickup.y-5);ctx.stroke();ctx.fillStyle='#fff8cf';ctx.strokeStyle='#392719';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pickup.x,top+size/2,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#392719';ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('+',pickup.x,top+size/2+1);ctx.restore();});}
function renderTanks(){(state.tanks||[]).forEach(drawTank);}
function visibleProjectile(){const sample=mode==='online'&&onlineProjectileSample?onlineProjectileSample.projectile:state.projectile;if(!sample||sample.concealed||!Number.isFinite(sample.x)||!Number.isFinite(sample.y))return null;if(mode==='online'&&onlineProjectileSample&&Number.isFinite(sample.vx)&&Number.isFinite(sample.vy))return predictProjectile(sample,Math.min((performance.now()-onlineProjectileSample.receivedAt)/1000,.1));return sample;}
function renderProjectiles(){const projectile=visibleProjectile();if(!projectile)return;const id=WEAPON_REGISTRY[projectile.weaponId]?projectile.weaponId:'shell',heading=Math.atan2(projectile.vy||0,projectile.vx||1);ctx.save();ctx.translate(projectile.x,projectile.y);ctx.rotate(heading);const speed=Math.hypot(projectile.vx||0,projectile.vy||0),trail=Math.min(28,10+speed/30),glow=id==='homing'?'#ff7548':'#ffcf62';const flame=ctx.createLinearGradient(-trail,0,0,0);flame.addColorStop(0,'rgba(255,91,45,0)');flame.addColorStop(.55,glow);flame.addColorStop(1,'#fff7c2');ctx.fillStyle=flame;ctx.beginPath();ctx.moveTo(-trail,0);ctx.lineTo(-4,-4);ctx.lineTo(-2,4);ctx.closePath();ctx.fill();ctx.shadowColor=glow;ctx.shadowBlur=14;const metal=ctx.createLinearGradient(0,-9,0,9);metal.addColorStop(0,'#fff4c2');metal.addColorStop(.35,'#9fa8a2');metal.addColorStop(1,'#27332e');ctx.fillStyle=metal;ctx.strokeStyle='#fff0a5';ctx.lineWidth=2;if(id==='homing'){ctx.beginPath();ctx.moveTo(13,0);ctx.quadraticCurveTo(7,-7,-5,-6);ctx.lineTo(-9,-10);ctx.lineTo(-8,-4);ctx.lineTo(-8,4);ctx.lineTo(-9,10);ctx.lineTo(-5,6);ctx.quadraticCurveTo(7,7,13,0);ctx.closePath();}else{const length=id==='heavy-shell'?18:14,radius=id==='heavy-shell'?8:6;ctx.beginPath();ctx.moveTo(length/2,0);ctx.quadraticCurveTo(length/4,-radius,-length/2,-radius);ctx.quadraticCurveTo(-length/2,radius,length/2,0);ctx.closePath();}ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,.75)';ctx.beginPath();ctx.ellipse(2,-3,4,1.5,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function render(){renderArena();renderEffects();renderPickups();renderTanks();renderProjectiles();}

function syncInventory(locked){const side=mode==='online'?(mySide??state.activePlayer):state.activePlayer,items=Array.isArray(state.inventories?.[side])?state.inventories[side]:[],box=document.querySelector('#inventory');box.replaceChildren();items.forEach(id=>{const item=POWER_UP_CATALOG[id];if(!item)return;const button=document.createElement('button'),unavailable=item.onlineOnly&&mode!=='online';button.type='button';button.textContent=unavailable?`${item.label} (online only)`:item.label;button.disabled=locked||unavailable;if(unavailable)button.title='This power-up can only be activated in an online room.';button.addEventListener('click',()=>usePowerUp(id));box.append(button);});if(!box.children.length)box.textContent='Empty — drive over a pickup';const requested=state.equippedWeapons?.[side]||'shell',weapon=WEAPON_REGISTRY[requested]||WEAPON_REGISTRY.shell,weaponId=weapon.id,ammo=weapon.ammo.unlimited?'Unlimited':String(state.weaponAmmo?.[side]?.[weaponId]||0);document.querySelector('#weapon-status').textContent=`Weapon: ${weapon.label} · ${ammo}`;document.querySelector('#ammo-status').textContent=weapon.ammo.unlimited?'Unlimited ammunition':`${ammo} rounds remaining`;document.querySelector('#fullscreen-ammo').textContent=weapon.ammo.unlimited?'Unlimited':`${ammo} rounds`;for(const select of [document.querySelector('#weapon-select'),document.querySelector('#fullscreen-weapon')]){select.value=weaponId;select.disabled=locked;}const effects=Array.isArray(state.activeEffects?.[side])?state.activeEffects[side]:[];document.querySelector('#effect-status').textContent=effects.length?effects.map(effect=>effect.effect==='absorb'?`Shield ${effect.remainingTurns??0} turns, ${effect.remainingCapacity??0} capacity`:`${POWER_UP_CATALOG[effect.id]?.label||'Effect'} ${effect.remainingTurns??0} turns`).join(' · '):'No active effects';}
function chooseWeapon(id){if(mode==='online')command('select-weapon',{weaponId:id});else selectWeapon(state,state.activePlayer,id);sync();render();}
for(const select of [document.querySelector('#weapon-select'),document.querySelector('#fullscreen-weapon')]){Object.values(WEAPON_REGISTRY).forEach(weapon=>{const option=document.createElement('option');option.value=weapon.id;option.textContent=weapon.label;select.append(option);});select.addEventListener('change',event=>chooseWeapon(event.target.value));}
function usePowerUp(id){const item=POWER_UP_CATALOG[id];if(!item||item.onlineOnly&&mode!=='online')return;if(mode==='online'){command(item.kind==='weapon'?'equip':'activate',{itemId:id});return;}const result=activatePowerUp(state,state.activePlayer,id);if(result?.consumesTurn){endTurnEffects(state,state.activePlayer);advancePickupSchedule(state);beginTurn(state,1-state.activePlayer);}sync();render();}
let announcedImpactSerial=0,previousAnnouncement='',previousEffects=[[],[]],previousHealth=[100,100],previousWeapons=['shell','shell'];
function tankHealth(index){const value=state.tanks?.[index]?.health;return Number.isFinite(value)?Math.max(0,Math.min(100,value)):0;}
function syncTankHud(){[0,1].forEach(index=>{const health=tankHealth(index),bar=document.querySelector(index?'#health-bar-right':'#health-bar-left');document.querySelector(index?'#health-right':'#health-left').textContent=health;bar.style.width=`${health}%`;bar.style.background=health>50?'#78d294':health>0?'#ffc65c':'#df604f';});}
function syncImpactHud(){if((state.impactSerial||0)<lastImpactSerial)lastImpactSerial=0;if(state.lastImpact?.serial>lastImpactSerial){lastImpactSerial=state.lastImpact.serial;const callout=document.querySelector('#impact-callout'),damage=Number(state.lastImpact.totalDamage)||0;callout.textContent=damage?`${damage} DAMAGE`:'NO DAMAGE';callout.classList.remove('show');void callout.offsetWidth;callout.classList.add('show');}}
function syncArenaHud(){const active=state.activePlayer===1?1:0,tank=state.tanks?.[active]||{},concealed=Boolean(tank.concealed);document.querySelector('#active-player').textContent=`Player ${active+1}`;document.querySelector('#angle').textContent=concealed||!Number.isFinite(tank.angle)?'—':`${tank.angle}°`;document.querySelector('#power').textContent=concealed||!Number.isFinite(tank.power)?'—':`${tank.power}%`;document.querySelector('#active-flag').textContent=state.phase==='game-over'?(state.draw?'Draw':`Player ${(state.winner??0)+1} wins`):`Player ${active+1} turn`;arena.dataset.active=active;arena.dataset.phase=state.phase;const description=index=>{const hidden=state.tanks?.[index]?.concealed?' and position concealed':'';const shield=(state.activeEffects?.[index]||[]).find(effect=>effect.effect==='absorb');return `${hidden}${shield?` and shield with ${shield.remainingTurns??0} turns and ${shield.remainingCapacity??0} capacity`:' and no shield'}`;};canvas.setAttribute('aria-label',`Battle Tanks arena. Player ${active+1} is active. Player 1 has ${tankHealth(0)} health${description(0)}; Player 2 has ${tankHealth(1)} health${description(1)}.`);}
function syncEffectsHud(){const shields=[0,1].map(index=>{const shield=(state.activeEffects?.[index]||[]).find(effect=>effect.effect==='absorb');return shield?`Player ${index+1} shield: ${shield.remainingTurns??0} turns, ${shield.remainingCapacity??0} capacity`:'';}).filter(Boolean);status.textContent=[state.opponentConcealed?'Opponent concealed.':state.announcement,...shields].filter(Boolean).join(' ');}
function announceStateChanges(){const messages=[];if(state.lastImpact?.serial>announcedImpactSerial){announcedImpactSerial=state.lastImpact.serial;const absorbed=(state.lastImpact.affected||[]).reduce((sum,item)=>sum+(Number(item.absorbedDamage)||0),0);if(absorbed)messages.push(`Shields absorbed ${absorbed} damage.`);}if(state.announcement&&state.announcement!==previousAnnouncement)messages.push(state.announcement);[0,1].forEach(index=>{const health=tankHealth(index);if(health>previousHealth[index])messages.push(`Player ${index+1} healed ${health-previousHealth[index]} health.`);const oldShield=previousEffects[index].find(effect=>effect.effect==='absorb'),shield=(state.activeEffects?.[index]||[]).find(effect=>effect.effect==='absorb');if(oldShield&&shield&&shield.remainingCapacity<oldShield.remainingCapacity)messages.push(`Player ${index+1} shield absorbed ${oldShield.remainingCapacity-shield.remainingCapacity} damage.`);previousEffects[index].forEach(effect=>{if(!(state.activeEffects?.[index]||[]).some(current=>current.id===effect.id))messages.push(`${POWER_UP_CATALOG[effect.id]?.label||'Effect'} expired for Player ${index+1}.`);});const weapon=state.equippedWeapons?.[index]||'shell';if(weapon!==previousWeapons[index])messages.push(`Player ${index+1} selected ${WEAPON_REGISTRY[weapon]?.label||'Standard shell'}.`);previousHealth[index]=health;previousEffects[index]=(state.activeEffects?.[index]||[]).map(effect=>({...effect}));previousWeapons[index]=weapon;});previousAnnouncement=state.announcement||'';if(messages.length)document.querySelector('#pickup-announcement').textContent=messages.join(' ');}
function syncControls(){const locked=state.phase!=='aiming'||(mode==='online'&&(mySide!==state.activePlayer||state.paused));document.querySelectorAll('[data-action],[data-move-direction]').forEach(button=>button.disabled=locked);fire.disabled=locked;fullscreenFire.disabled=locked;syncInventory(locked);rematch.hidden=state.phase!=='game-over';shareButton.hidden=state.phase!=='game-over';}
function sync(){syncAcquisitionEvents();syncTankHud();syncImpactHud();syncArenaHud();syncEffectsHud();announceStateChanges();syncControls();}

function sendOnline(message){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message));}
function command(type,extra={}){sendOnline({type,matchId:state.matchId,turnId:state.turnId,...extra});}
function act(action){if(currentPowerCard)return;if(mode==='online'){if(action==='forward'||action==='backward')command('move',{direction:action});else{const tank=state.tanks[state.activePlayer];if(!tank||tank.concealed)return;const angle=tank.angle+(action==='aim-up'?2:action==='aim-down'?-2:0),power=tank.power+(action==='power-up'?5:action==='power-down'?-5:0);command('aim',{angle:Math.max(10,Math.min(80,angle)),power:Math.max(20,Math.min(100,power))});}return;}if(action==='forward'||action==='backward')moveTank(state,action);else if(action==='aim-up')adjustAim(state,2);else if(action==='aim-down')adjustAim(state,-2);else if(action==='power-up')adjustPower(state,5);else if(action==='power-down')adjustPower(state,-5);sync();render();}
function moveAction(direction){return direction==='left'?(state.activePlayer?'forward':'backward'):(state.activePlayer?'backward':'forward');}document.querySelectorAll('[data-move-direction]').forEach(button=>button.addEventListener('click',()=>act(moveAction(button.dataset.moveDirection))));document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>act(button.dataset.action)));function shoot(){if(currentPowerCard)return;if(mode==='online')command('fire');else fireProjectile(state);sync();}fire.addEventListener('click',shoot);fullscreenFire.addEventListener('click',shoot);rematch.addEventListener('click',()=>{if(mode==='online')sendOnline({type:'rematch'});else{resetMatch(state);lastImpactSerial=0;}sync();render();});
document.addEventListener('keydown',event=>{if(event.code==='Escape'&&currentPowerCard){event.preventDefault();dismissPowerCard();return;}if(event.repeat||currentPowerCard||['BUTTON','INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;const horizontal=event.code==='ArrowLeft'?(state.activePlayer?'forward':'backward'):event.code==='ArrowRight'?(state.activePlayer?'backward':'forward'):null;const actions={KeyA:'backward',KeyD:'forward',KeyW:'aim-up',KeyS:'aim-down',KeyQ:'power-down',KeyE:'power-up',ArrowUp:'aim-up',ArrowDown:'aim-down',Minus:'power-down',NumpadSubtract:'power-down',Equal:'power-up',NumpadAdd:'power-up'};const action=horizontal||actions[event.code];if(action){event.preventDefault();act(action);}else if(event.code==='Space'){event.preventDefault();shoot();}});
canvas.addEventListener('pointerdown',event=>{if(mode==='online'||state.phase!=='aiming')return;dragging=true;canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!dragging||state.phase!=='aiming')return;const rect=canvas.getBoundingClientRect(),logicalX=(event.clientX-rect.left)*WIDTH/rect.width,tank=state.tanks[state.activePlayer],bounds=tankBounds(state,state.activePlayer);tank.x=Math.max(bounds.min,Math.min(bounds.max,logicalX-TANK_W/2));tank.y=tankYAt(state,tank);collectPickup(state,state.activePlayer);sync();render();});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
function optionalResultStatistics(statistics,side){if(!statistics)return {};const result={},fields=['powerUpsAcquired','powerUpsUsed','shieldDamageAbsorbed','healthRestored','invisibilityActivations','laserRicochetHits','laserSelfDamage','homingHits','heavyProjectileMaxDamage','poweredHits'],weapons=statistics.weapons?.[side];if(weapons&&typeof weapons==='object')result.weapons=weapons;for(const name of fields)if(Number.isSafeInteger(statistics[name]?.[side]))result[name]=statistics[name][side];const types=statistics.powerUpTypesUsed?.[side];result.powerUpTypesUsed=Array.isArray(types)?[...new Set(types.filter(id=>POWER_UP_CATALOG[id]))]:[];return result;}
async function submitResult(){if(state.resultSubmitted||state.phase!=='game-over'||state.draw||!window.Arcade?.user())return;state.resultSubmitted=true;const damageTaken=state.damageTaken?.[0]||0,details={mode:'local',winner:state.winner+1,turns:state.shots,shots:state.shots,hits:state.hits,seconds:Math.max(1,Math.min(7200,Math.round((Date.now()-state.startedAt)/1000))),damageTaken,...optionalResultStatistics(state.statistics,0),invisibilityActivations:0};try{await window.Arcade.record({game:'battletanks',won:state.winner===0,details});}catch{/* Saving an arcade result must never block a local rematch. */}}
function setupColorControls(){document.querySelectorAll('.player-color').forEach((picker,index)=>{const trigger=picker.querySelector('.color-trigger'),menu=picker.querySelector('.color-menu'),swatches=picker.querySelector('.swatches');trigger.style.setProperty('--selected-color',tankColors[index]);trigger.addEventListener('click',()=>{const opening=menu.hidden;document.querySelectorAll('.color-menu').forEach(item=>item.hidden=true);menu.hidden=!opening;trigger.setAttribute('aria-expanded',String(opening));});window.ArcadeGameColors.forEach(color=>{const button=document.createElement('button');button.type='button';button.className='swatch';button.style.setProperty('--swatch',color.value);button.setAttribute('aria-label',`${color.name} Player ${index+1} tank`);button.setAttribute('aria-pressed',String(color.value===tankColors[index]));button.addEventListener('click',()=>{tankColors[index]=color.value;if(mode==='online'&&index===mySide)sendOnline({type:'color',color:color.value});trigger.style.setProperty('--selected-color',color.value);swatches.querySelectorAll('.swatch').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));menu.hidden=true;trigger.setAttribute('aria-expanded','false');trigger.focus();render();});swatches.append(button);});});}
document.addEventListener('click',event=>{if(event.target.closest('.player-color'))return;document.querySelectorAll('.color-menu').forEach(menu=>menu.hidden=true);document.querySelectorAll('.color-trigger').forEach(trigger=>trigger.setAttribute('aria-expanded','false'));});
document.addEventListener('keydown',event=>{if(event.code!=='Escape'||event.defaultPrevented)return;document.querySelectorAll('.color-menu').forEach(menu=>menu.hidden=true);document.querySelectorAll('.color-trigger').forEach(trigger=>trigger.setAttribute('aria-expanded','false'));if(arena.classList.contains('is-fullscreen'))setFullscreenState(false);});
function setFullscreenState(active){arena.classList.toggle('is-fullscreen',active&&document.fullscreenElement!==arena);document.body.classList.toggle('arena-fullscreen',active);fullscreenButton.textContent=active?'Exit full screen':'Enter full screen';fullscreenButton.setAttribute('aria-pressed',String(active));}
fullscreenButton.addEventListener('click',async()=>{const active=document.fullscreenElement===arena||arena.classList.contains('is-fullscreen');if(active){if(document.fullscreenElement)await document.exitFullscreen();else setFullscreenState(false);return;}if(arena.requestFullscreen){try{await arena.requestFullscreen();return;}catch{/* CSS fallback supports browsers without element fullscreen. */}}setFullscreenState(true);});
arena.querySelector('.fullscreen-exit').addEventListener('click',()=>fullscreenButton.click());
document.addEventListener('fullscreenchange',()=>setFullscreenState(document.fullscreenElement===arena));
shareButton.addEventListener('click',async()=>{const image=document.createElement('canvas');image.width=1200;image.height=630;const card=image.getContext('2d');card.fillStyle='#f5f1e8';card.fillRect(0,0,1200,630);card.fillStyle='#20352f';card.font='700 32px system-ui';card.fillText('BATTLE TANKS',70,90);card.font='700 68px system-ui';card.fillText(`Player ${state.winner+1} wins!`,70,190);card.font='500 28px system-ui';card.fillText(`${state.shots} shots · ${state.hits} direct hits`,70,245);card.drawImage(canvas,650,95,480,270);try{await window.ResultShare.share({image,filename:'battle-tanks-result.png',title:'My Battle Tanks result',text:`Player ${state.winner+1} won Battle Tanks in ${state.shots} shots.`});}catch(error){if(error.name!=='AbortError')status.textContent='Could not share this result.';}});
const onlinePanel=document.querySelector('#online-panel'),lobby=document.querySelector('#online-lobby'),roomPanel=document.querySelector('#online-room'),connection=document.querySelector('#connection-state');
function setConnection(text,state=text==='Online'?'online':text==='Connecting'?'connecting':'offline'){OnlineRooms.setConnection(connection,text,state);}
function isSupportedState(incoming){return Boolean(incoming&&incoming.stateVersion===STATE_VERSION&&incoming.arena&&Array.isArray(incoming.tanks)&&incoming.tanks.length===2);}
function openSocket(action){if(socket&&socket.readyState<2)socket.close();const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(`${protocol}//${location.host}/ws/battle-tanks`);setConnection('Connecting');socket.addEventListener('open',()=>{setConnection('Online');sendOnline(action);});socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.type==='session'){onlineSession={roomCode:message.roomCode,playerToken:message.playerToken};mySide=message.side;sessionStorage.setItem('battle-tanks-session',JSON.stringify(onlineSession));document.querySelector('#current-room').textContent=message.roomCode;const side=document.querySelector('#player-side');side.dataset.side=message.side?'right':'left';side.querySelector('strong').textContent=`Player ${message.side+1}`;lobby.hidden=true;roomPanel.hidden=false;history.replaceState(null,'',`?room=${message.roomCode}`);}else if(message.type==='power-up-acquired'){if(message.matchId===state.matchId)queueAcquisitionEvents([message.event]);}else if(message.type==='state'){if(!isSupportedState(message.state)){status.textContent='This room uses an unsupported game state version. Leaving room.';leaveRoom(false);status.textContent='This room uses an unsupported game state version. Please update before joining again.';return;}onlineProjectileSample=message.state.projectile?{projectile:{...message.state.projectile},receivedAt:performance.now()}:null;Object.assign(state,message.state);sync();render();}else if(message.type==='room-status'){const names=message.gamertags||[];document.querySelector('#online-players').textContent=`${names[0]||'Player 1'} ${message.players[0]?'●':'○'}  vs  ${names[1]||'Waiting…'} ${message.players[1]?'●':'○'}`;}else if(message.type==='peer-left'){status.textContent='Opponent disconnected. Waiting for reconnection…';}else if(message.type==='room-closed'){status.textContent=message.reason;leaveRoom(false);}else if(message.type==='error')status.textContent=message.message;});socket.addEventListener('close',()=>{setConnection('Offline');if(mode==='online'&&onlineSession)setTimeout(()=>openSocket({type:'resume',...onlineSession}),800);});}
async function refreshRooms(){const list=document.querySelector('#room-list');list.innerHTML='<p>Loading available rooms…</p>';try{const response=await fetch('../api/battle-tanks/rooms'),data=await response.json();OnlineRooms.renderRooms(list,data.rooms,code=>openSocket({type:'join-room',roomCode:code}));}catch{list.innerHTML='<p>Online rooms require the arcade server.</p>';}}
function leaveRoom(notify=true){if(notify)sendOnline({type:'leave'});socket?.close();socket=null;onlineSession=null;mySide=null;onlineProjectileSample=null;sessionStorage.removeItem('battle-tanks-session');lobby.hidden=false;roomPanel.hidden=true;history.replaceState(null,'',OnlineRooms.clearInvite());resetMatch(state);lastImpactSerial=0;sync();}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mode===mode)));onlinePanel.hidden=mode!=='online';if(mode==='local'){leaveRoom();return;}refreshRooms();const saved=JSON.parse(sessionStorage.getItem('battle-tanks-session')||'null'),invite=new URLSearchParams(location.search).get('room');if(saved)openSocket({type:'resume',...saved});else if(invite)document.querySelector('#room-code').value=invite;}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.mode)));document.querySelector('#refresh-rooms').addEventListener('click',refreshRooms);document.querySelector('#visibility').addEventListener('change',event=>document.querySelector('#room-passcode').hidden=event.target.value!=='private');document.querySelector('#create-room').addEventListener('click',()=>{const visibility=document.querySelector('#visibility').value,result=OnlineRooms.validateRoom(visibility,document.querySelector('#room-passcode').value);if(!result.ok){status.textContent=result.message;return;}openSocket({type:'create-room',visibility,passcode:result.passcode});});document.querySelector('#join-room').addEventListener('click',()=>{const result=OnlineRooms.validateJoin(document.querySelector('#room-code').value);if(!result.ok){status.textContent=result.message;return;}openSocket({type:'join-room',roomCode:result.code,passcode:document.querySelector('#join-passcode').value.trim()});});document.querySelector('#ready-online').addEventListener('click',()=>sendOnline({type:'ready'}));document.querySelector('#leave-room').addEventListener('click',()=>leaveRoom());document.querySelector('#copy-invite').addEventListener('click',async()=>{try{await OnlineRooms.copyInvite(onlineSession.roomCode);status.textContent='Invite link copied.';}catch{status.textContent='Could not copy the invite link. Copy it from the address bar instead.';}});
document.addEventListener('arcade:theme',event=>updateArenaTheme(event.detail.resolvedColorMode,event.detail.theme));
function frame(now){const elapsed=Math.min(.1,(now-last)/1000);last=now;if(mode==='local'&&state.phase==='projectile-flight'){accumulator+=elapsed;while(accumulator>=1/120&&state.phase==='projectile-flight'){stepPhysics(state,1/120);accumulator-=1/120;}sync();if(state.phase==='game-over')submitResult();}render();requestAnimationFrame(frame);}updateArenaTheme();setupColorControls();beginTurn(state,0);sync();requestAnimationFrame(frame);if(new URLSearchParams(location.search).has('room')||sessionStorage.getItem('battle-tanks-session'))setMode('online');
})(typeof globalThis!=='undefined'?globalThis:this);
