(function(root){
'use strict';
const WIDTH=960,HEIGHT=540,GROUND=488,GRAVITY=210,TANK_W=58,TANK_H=30,PROJECTILE_R=6,STARTING_HEALTH=100,DAMAGE=50;
const barrier={x:448,y:266,w:64,h:GROUND-266};
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
function createInitialState(){return{phase:'setup',activePlayer:0,tanks:[{x:115,y:GROUND-TANK_H,angle:45,power:60,health:STARTING_HEALTH},{x:WIDTH-115-TANK_W,y:GROUND-TANK_H,angle:45,power:60,health:STARTING_HEALTH}],projectile:null,winner:null,announcement:'Preparing the arena.'};}
function beginTurn(state,player=state.activePlayer){if(state.phase==='game-over')return false;state.activePlayer=player;state.phase='aiming';state.projectile=null;state.announcement=`Player ${player+1}: adjust your shot.`;return true;}
function tankBounds(player){return player===0?{min:0,max:barrier.x-TANK_W}:{min:barrier.x+barrier.w,max:WIDTH-TANK_W};}
function moveTank(state,direction,amount=8){if(state.phase!=='aiming')return false;const tank=state.tanks[state.activePlayer],bounds=tankBounds(state.activePlayer);tank.x=clamp(tank.x+(direction==='forward'?(state.activePlayer? -amount:amount):(state.activePlayer?amount:-amount)),bounds.min,bounds.max);return true;}
function adjustAim(state,delta){if(state.phase!=='aiming')return false;const tank=state.tanks[state.activePlayer];tank.angle=clamp(tank.angle+delta,10,80);return true;}
function adjustPower(state,delta){if(state.phase!=='aiming')return false;const tank=state.tanks[state.activePlayer];tank.power=clamp(tank.power+delta,20,100);return true;}
function fireProjectile(state){if(state.phase!=='aiming')return false;const tank=state.tanks[state.activePlayer],direction=state.activePlayer? -1:1,radians=tank.angle*Math.PI/180,speed=170+tank.power*3.2;state.projectile={x:tank.x+TANK_W/2+direction*32,y:tank.y-7,vx:Math.cos(radians)*speed*direction,vy:-Math.sin(radians)*speed,owner:state.activePlayer};state.phase='projectile-flight';state.announcement=`Player ${state.activePlayer+1} fired.`;return true;}
function circleRect(x,y,r,rect){return x+r>=rect.x&&x-r<=rect.x+rect.w&&y+r>=rect.y&&y-r<=rect.y+rect.h;}
function resolveShot(state,hit){state.projectile=null;if(hit&&hit.type==='tank'){const target=state.tanks[hit.index];target.health=Math.max(0,target.health-DAMAGE);if(target.health===0){state.phase='game-over';state.winner=1-hit.index;state.announcement=`Player ${state.winner+1} wins!`;return hit;}}state.activePlayer=1-state.activePlayer;state.phase='aiming';state.announcement=hit?.type==='tank'?`Direct hit! Player ${state.activePlayer+1}'s turn.`:`Shot ended. Player ${state.activePlayer+1}'s turn.`;return hit;}
function collisionAt(state,x,y){if(circleRect(x,y,PROJECTILE_R,barrier))return{type:'barrier'};for(let i=0;i<state.tanks.length;i++){const t=state.tanks[i];if(circleRect(x,y,PROJECTILE_R,{x:t.x,y:t.y,w:TANK_W,h:TANK_H}))return{type:'tank',index:i};}if(y+PROJECTILE_R>=GROUND)return{type:'terrain'};if(x+PROJECTILE_R<0||x-PROJECTILE_R>WIDTH||y+PROJECTILE_R<0||y-PROJECTILE_R>HEIGHT)return{type:'out-of-bounds'};return null;}
function stepPhysics(state,dt=1/120){if(state.phase!=='projectile-flight'||!state.projectile)return null;const p=state.projectile,dx=p.vx*dt,dy=p.vy*dt+.5*GRAVITY*dt*dt,steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/3));for(let i=1;i<=steps;i++){const f=i/steps,hit=collisionAt(state,p.x+dx*f,p.y+dy*f);if(hit){p.x+=dx*f;p.y+=dy*f;return resolveShot(state,hit);}}p.x+=dx;p.y+=dy;p.vy+=GRAVITY*dt;return null;}
function resetMatch(state){const fresh=createInitialState();Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,fresh);beginTurn(state,0);return state;}
const api={WIDTH,HEIGHT,GROUND,GRAVITY,TANK_W,TANK_H,PROJECTILE_R,STARTING_HEALTH,DAMAGE,barrier,createInitialState,beginTurn,tankBounds,moveTank,adjustAim,adjustPower,fireProjectile,collisionAt,stepPhysics,resolveShot,resetMatch};
if(typeof module!=='undefined'&&module.exports)module.exports=api;root.BattleTanksCore=api;
if(typeof document==='undefined')return;
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),status=document.querySelector('#status'),fire=document.querySelector('#fire'),rematch=document.querySelector('#rematch'),arena=document.querySelector('#arena');const state=createInitialState();let last=performance.now(),accumulator=0,dragging=false;
function render(){ctx.clearRect(0,0,WIDTH,HEIGHT);const sky=ctx.createLinearGradient(0,0,0,GROUND);sky.addColorStop(0,'#b9dadd');sky.addColorStop(1,'#edf0d8');ctx.fillStyle=sky;ctx.fillRect(0,0,WIDTH,GROUND);ctx.fillStyle='#79935c';ctx.fillRect(0,GROUND,WIDTH,HEIGHT-GROUND);ctx.fillStyle='#566c46';ctx.fillRect(0,GROUND,WIDTH,7);ctx.fillStyle='#786c61';ctx.fillRect(barrier.x,barrier.y,barrier.w,barrier.h);ctx.fillStyle='#62584f';for(let y=barrier.y+12;y<GROUND;y+=24)ctx.fillRect(barrier.x,y,barrier.w,3);
state.tanks.forEach((tank,i)=>{const active=state.phase==='aiming'&&i===state.activePlayer,dir=i? -1:1,cx=tank.x+TANK_W/2,cy=tank.y;ctx.save();ctx.fillStyle=i?'#dc7655':'#e7b94e';ctx.fillRect(tank.x,tank.y+8,TANK_W,TANK_H-8);ctx.beginPath();ctx.arc(cx,tank.y+8,16,Math.PI,0);ctx.fill();ctx.strokeStyle=active?'#fff':'#25352f';ctx.lineWidth=active?4:2;ctx.strokeRect(tank.x-3,tank.y+5,TANK_W+6,TANK_H+1);const rad=tank.angle*Math.PI/180;ctx.strokeStyle='#25352f';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(cx,cy+5);ctx.lineTo(cx+Math.cos(rad)*42*dir,cy-Math.sin(rad)*42);ctx.stroke();if(active){ctx.setLineDash([7,7]);ctx.strokeStyle='rgba(27,70,60,.7)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx+Math.cos(rad)*46*dir,cy-Math.sin(rad)*46);ctx.lineTo(cx+Math.cos(rad)*105*dir,cy-Math.sin(rad)*105);ctx.stroke();}ctx.restore();});
if(state.projectile){ctx.fillStyle='#1d2925';ctx.beginPath();ctx.arc(state.projectile.x,state.projectile.y,PROJECTILE_R,0,Math.PI*2);ctx.fill();} }
function sync(){const tank=state.tanks[state.activePlayer];document.querySelector('#health-left').textContent=state.tanks[0].health;document.querySelector('#health-right').textContent=state.tanks[1].health;document.querySelector('#active-player').textContent=`Player ${state.activePlayer+1}`;document.querySelector('#angle').textContent=`${tank.angle}°`;document.querySelector('#power').textContent=`${tank.power}%`;document.querySelector('#active-flag').textContent=state.phase==='game-over'?`Player ${state.winner+1} wins`:`Player ${state.activePlayer+1} turn`;arena.dataset.active=state.activePlayer;canvas.setAttribute('aria-label',`Battle Tanks arena. Player ${state.activePlayer+1} is active. Player 1 has ${state.tanks[0].health} health; Player 2 has ${state.tanks[1].health} health.`);status.textContent=state.announcement;const locked=state.phase!=='aiming';document.querySelectorAll('[data-action]').forEach(button=>button.disabled=locked);fire.disabled=locked;rematch.hidden=state.phase!=='game-over';}
function act(action){if(action==='forward'||action==='backward')moveTank(state,action);else if(action==='aim-up')adjustAim(state,2);else if(action==='aim-down')adjustAim(state,-2);else if(action==='power-up')adjustPower(state,5);else if(action==='power-down')adjustPower(state,-5);sync();render();}
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('pointerdown',event=>{event.preventDefault();act(button.dataset.action);}));fire.addEventListener('click',()=>{fireProjectile(state);sync();});rematch.addEventListener('click',()=>{resetMatch(state);sync();render();});
document.addEventListener('keydown',event=>{if(event.repeat||['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;const actions={KeyA:'backward',KeyD:'forward',KeyW:'aim-up',KeyS:'aim-down',KeyQ:'power-down',KeyE:'power-up'};if(actions[event.code]){event.preventDefault();act(actions[event.code]);}else if(event.code==='Space'){event.preventDefault();if(fireProjectile(state))sync();}});
canvas.addEventListener('pointerdown',event=>{if(state.phase!=='aiming')return;dragging=true;canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!dragging||state.phase!=='aiming')return;const rect=canvas.getBoundingClientRect(),logicalX=(event.clientX-rect.left)*WIDTH/rect.width,tank=state.tanks[state.activePlayer],bounds=tankBounds(state.activePlayer);tank.x=clamp(logicalX-TANK_W/2,bounds.min,bounds.max);sync();render();});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
function frame(now){const elapsed=Math.min(.1,(now-last)/1000);last=now;if(state.phase==='projectile-flight'){accumulator+=elapsed;while(accumulator>=1/120&&state.phase==='projectile-flight'){stepPhysics(state,1/120);accumulator-=1/120;}sync();}render();requestAnimationFrame(frame);}beginTurn(state,0);sync();requestAnimationFrame(frame);
})(typeof globalThis!=='undefined'?globalThis:this);
