'use strict';
const crypto = require('node:crypto');
const ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', token=()=>crypto.randomBytes(24).toString('base64url');
const winner=board=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(line=>board[line[0]]&&line.every(cell=>board[cell]===board[line[0]]))||null;
class TicTacToeRooms {
 constructor({reconnectMs=15000,roomTimeoutMs=1800000,random=Math.random}={}){this.rooms=new Map();Object.assign(this,{reconnectMs,roomTimeoutMs,random});}
 makeCode(){let code;do{code=Array.from({length:5},()=>ALPHABET[Math.floor(this.random()*ALPHABET.length)]).join('');}while(this.rooms.has(code));return code;}
 makePlayer(socket,side,gamertag){return{token:token(),socket,side,gamertag:String(gamertag||''),connected:true,ready:false,disconnectedAt:null};}
 create(socket,{visibility='private',passcode='',gamertag=''}={}){const pub=visibility==='public',secret=String(passcode||'').trim();if(!pub&&(secret.length<4||secret.length>32))throw new Error('Private room passcodes must be 4–32 characters.');const code=this.makeCode(),player=this.makePlayer(socket,0,gamertag),room={code,visibility:pub?'public':'private',passcode:pub?'':secret,players:[player,null],board:Array(9).fill(null),turn:0,running:false,over:false,winner:null,winningLine:[],colors:['#fffdf8','#d76b45'],started:null,createdAt:Date.now(),touchedAt:Date.now(),starter:1};this.rooms.set(code,room);return{room,player};}
 join(value,socket,passcode='',gamertag=''){const room=this.rooms.get(String(value||'').toUpperCase());if(!room)throw new Error('Room not found. Check the code and try again.');if(room.players[1])throw new Error('That room is already full.');if(room.visibility==='private'&&String(passcode||'').trim()!==room.passcode)throw new Error('That passcode is incorrect.');const player=this.makePlayer(socket,1,gamertag);room.players[1]=player;room.touchedAt=Date.now();return{room,player};}
 resume(code,playerToken,socket){const room=this.rooms.get(String(code||'').toUpperCase()),player=room?.players.find(item=>item?.token===playerToken);if(!player)throw new Error('This game session is no longer available.');player.socket?.close(4001,'Session resumed elsewhere');Object.assign(player,{socket,connected:true,disconnectedAt:null});return{room,player};}
 publicRooms(){return[...this.rooms.values()].filter(room=>room.visibility==='public'&&!room.players[1]).map(room=>({code:room.code,players:room.players.filter(item=>item?.connected).length,createdAt:room.createdAt})).sort((a,b)=>b.createdAt-a.createdAt);}
 ready(room,player){if(room.running&&!room.over)throw new Error('The match is already in progress.');player.ready=true;if(room.players.every(item=>item?.ready&&item.connected)){room.players.forEach(item=>item.ready=false);room.board.fill(null);room.starter=1-room.starter;room.turn=room.starter;room.running=true;room.over=false;room.winner=null;room.winningLine=[];room.started=Date.now();return true;}return false;}
 rematch(room){if(!room.players.every(item=>item?.connected))throw new Error('Both players must be connected to start a rematch.');if(room.running&&!room.over)return true;if(!room.over)throw new Error('The match must be finished before starting a rematch.');room.players.forEach(item=>item.ready=false);room.board.fill(null);room.starter=1-room.starter;room.turn=room.starter;room.running=true;room.over=false;room.winner=null;room.winningLine=[];room.started=Date.now();room.touchedAt=Date.now();return true;}
 move(room,player,cell){if(!room.running||room.over)throw new Error('The match is not active.');if(player.side!==room.turn)throw new Error('Wait for your turn.');if(!Number.isInteger(cell)||cell<0||cell>8||room.board[cell])throw new Error('That square is unavailable.');room.board[cell]=player.side?'O':'X';const line=winner(room.board);if(line){Object.assign(room,{running:false,over:true,winner:player.side,winningLine:line});}else if(room.board.every(Boolean)){Object.assign(room,{running:false,over:true,winner:null,winningLine:[]});}else room.turn=1-room.turn;room.touchedAt=Date.now();}
 color(room,player,color){if(/^#[0-9a-f]{6}$/i.test(color))room.colors[player.side]=color;}
 state(room){return{board:room.board,turn:room.turn,running:room.running,over:room.over,winner:room.winner,winningLine:room.winningLine,colors:room.colors,started:room.started};}
 broadcast(room,message){const body=JSON.stringify(message);room.players.forEach(item=>{if(item?.socket?.readyState===1)item.socket.send(body);});}
 disconnect(room,player,socket=player.socket){if(player.socket!==socket)return false;Object.assign(player,{connected:false,socket:null,disconnectedAt:Date.now()});return true;}
 tick(now=Date.now()){for(const[code,room]of this.rooms){const expired=room.players.some(item=>item&&!item.connected&&now-item.disconnectedAt>this.reconnectMs);if(expired||now-room.touchedAt>this.roomTimeoutMs){this.broadcast(room,{type:'room-closed',reason:expired?'An opponent did not reconnect in time.':'Room expired.'});this.rooms.delete(code);}}}
}
module.exports={TicTacToeRooms,winner};
